### ISSUE TITLE
Update russian translation for keyboard-indicator

### ISSUE THREAD

**Issue by IgorPolyakov** [ubports/indicator-keyboard#8]
### Illustrations

Indicator-keyboard haven't update russian translate.

But it has 100% [translate](https://translate.ubports.com/projects/ubports/indicator-keyboard/ru/#overview)

- Device: hammerhead (nexus 5)
- Channel: dev
- Build: 2018-10-30/2

### Steps to reproduce

Pull the main menu down
### Expected behavior
See text 'Раскладка клавиатуры'

### Actual behavior
See text 'Keyboard Layout'

### Logfiles and additional information
![screenshot20181102_140221228](https://user-images.githubusercontent.com/2613581/47899059-e86c0500-deaa-11e8-9008-661b7d8f0628.png)

**Comment by Flohack74** [comment]
See here: https://translate.ubports.com/translate/ubports/indicator-keyboard/ru/?checksum=&offset=&q=Layout&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=
The problem is not that the translation was not done. Maybe someone forgot to localize the string in the code? But then it would not be in Weblate.

**Comment by Flohack74** [comment]
![image](https://user-images.githubusercontent.com/16186470/47915196-64ae1a80-dea2-11e8-85ea-2f51636feb58.png)

**Comment by Flohack74** [comment]
Hopefully fixed in #22
